### ISSUE TITLE
Option to disable automation?

### ISSUE THREAD

**Issue by jcolemanquotient** [krysztalzg/ThandulsTogglableEffects#13]
I have a barbarian in my games with some extra effects on rage - extra resistances and such, like BearBarians get. It's been causing some slight problems when combined with the automation system, since the two effects both activate at once. Oddly, it adds +22 to the damage, instead of +4...

I could just have the custom effect just add the difference resistances, but what if I want to remove one? Not really the case here, but it might happen in the future somehow.

I'm running into a similar problem with Shield, as well - I've already set up the dynamic effects for it on most of my actors, so when I cast Shield it pops up a duplicate shield effect, giving +10 to AC instead. I can just go through and manually reimport every Shield spell, but... I'd like to not have to do that.

Is it possible that a toggle for the automated effects could be implemented - or even better, maybe something that checks if an effect is already set, if possible? This module is an enormous help when I don't have the effects set up in advance, but I'd like to be able to set them up in my own way too.

**Comment by kszczepanskidev** [comment]
The module checks for existing effect, but effects can have any name, so it only looks for effect that was applied by the module and ignores anything added to actor by other sources.
