### ISSUE TITLE
Guidance improvements.

### ISSUE THREAD

**Issue by mafddawg** [krysztalzg/ThandulsTogglableEffects#16]
Two issues I have found with the guidance cantrip:
1. It doesn't apply to initiative checks.
2. It persists after making an ability check

The second one is low priority, you just need to remember to cancel it after using it. The other is different since initiative is something that can't be edited like you can normal ability checks.

**Comment by kszczepanskidev** [comment]
Thanks for feedback.
1. Good catch, seems that the 5e system doesn't add the roll bonus to initiative. I will add this bonus separately to initiative and will hope they wont change it so it won't double 🙂 
2. Yeah, I've created this module with no dependencies in mind, but more and more DAE features are to good to not use them 😄

**Comment by mafddawg** [comment]
Thanks for the quick response.
I did a quick test and the initiative issue I refer to is seems to be foundry core. There are 2 ways to roll initiative in foundry core, either from your character sheet, or from the initiative tracker.
