### ISSUE TITLE
Mage Armor toggles Hybrid Transformation

### ISSUE THREAD

**Issue by Fraxinus1753** [krysztalzg/ThandulsTogglableEffects#17]
Thanks for the great module! I just discovered it today. I tried with the latest version (1.2.8), and the Mage Armor toggle does not trigger the Mage Armor effect, but Hybrid Transformation instead. All other effects seemed to work fine. I tried it with no other module enabled, same issue.

**Comment by kszczepanskidev** [comment]
Thanks for reporting. I see where the issue comes from and will fix later today
