### ISSUE TITLE
Priority issues with AC calculation

### ISSUE THREAD

**Issue by Fraxinus1753** [krysztalzg/ThandulsTogglableEffects#18]
Hey, thanks for the very quick update with your Mages, not beasts version! I noticed another issue, however: the priority for mage Armor is too high, resulting in issues in AC calculation. Indeed, the priority is set at 40 (which is the default for "upgrade" effects), while priority for shield and other "add" effects is 20. 

As a result, those two effects do not combine. Let's say I have a character with 14 dexterity and no armor, and apply both effects. In your configuration, Foundry will first apply shield (priority 20), resulting in an AC of 17 (10 + 2 for dex + 5 for shield), then check the AC from the mage armor effect (priority 40) and see that it is 15 (13 + 2 for dex) and therefore keep the 17 AC as it's higher than 15. This issue will arise with any other "add" effect that people might create within Foundry (e.g. from bracers of defense or ring of protection), as most people will keep the default priority of 20 for add effects. 

So you want a low priority for Mage armor (e.g. 5), so that Foundry first applies the 13 + dex formula, then adds the +5 from shield (or other "add" effects) on top of that. 

That's the only priority issue I saw.

**Comment by kszczepanskidev** [comment]
Thanks for pointing this out, that's another thing that got missed while trying to implement this module without relying on other modules (DAE introduces effects priorities) 😄 Looks like I need to start a game with more magic users to have realtime testers for this.

**Comment by Fraxinus1753** [comment]
Happy to help! I didn't know priorities relied on DAE, I thought they were implemented in Foundry core. 

If you're in doubt when configuring your effects, you could check the DAE SRD module by Kandashi to see how he did it. He implemented quite a lot of spells and other effects and knows very well the subtleties of the system, so everything is really well done from what I've seen (but not as easy to trigger as your toggle system).
