### ISSUE TITLE
Bug with minimal UI

### ISSUE THREAD

**Issue by Fridan99** [krysztalzg/ThandulsTogglableEffects#19]
![screenshot](https://user-images.githubusercontent.com/86131373/124395364-a64e8d80-dcfb-11eb-836f-0e623471323f.jpg)

**Comment by Fridan99** [comment]
That bug does not happen all the time..... sometimes the icon appears this big, sometimes not.... the conflict can be due to the minimal UI module

**Comment by kszczepanskidev** [comment]
This is weird as I was not able to reproduce the issue and my module is not doing anything in particular in terms of the icon beside drawing the .svg. I've updated the css, so it should work better now and always fill into the container.
