### ISSUE TITLE
Add an option to only show the icon to the GM?

### ISSUE THREAD

**Issue by fiagewinnt** [krysztalzg/ThandulsTogglableEffects#3]
Hi! 
I just wanted to ask if it might be possible to add an option to only show the icon to activate the effects panel to GM users? One of my players gave themselves buffs without them or me noticing because he was curious what the icons would do and then it kind of bugged out. Trying to disable them in the character sheets effects tab didn't do anything so I had to disable the mod alltogether to finally get rid of all the effects he unjustifiably gave himself.

**Comment by kszczepanskidev** [comment]
Thanks for feedback, this is definitely good idea for a setting, look up to an update this weekend 🙂
