### ISSUE TITLE
Pass Without Trace effect incorrect

### ISSUE THREAD

**Issue by BlitzKraig** [krysztalzg/ThandulsTogglableEffects#5]
My understanding is Pass Without Trace should add 10 to all stealth rolls (`data.skills.ste.mod Add 10`)

However, the current effect is doing `data.skills.ste.value Add Not Proficient`

I'm not fully up to speed on active effects, but the final result seems to add 2 to the Skill, instead of 10 to the skill modifier

**Comment by kszczepanskidev** [comment]
Yeah, the `.value` property worked differently in previous version of dnd5e(?) and it's not working anymore. I've consulted with devs and there's no way to add flat bonus to specific skill check, so I need to check for DAE module and enable Pass Without Trace effect only with DAE installed.
This was also reported recently here: https://github.com/krysztalzg/ThandulsTogglableEffects/pull/4

**Comment by BlitzKraig** [comment]
Ah, sorry, didn't think to check closed issues.

Also, as with the other issue author, forgot that DAE does some extra magic in that department.

Thanks

**Comment by kszczepanskidev** [comment]
This should be fixed now in [1.2.5](https://github.com/krysztalzg/ThandulsTogglableEffects/releases/tag/1.2.5).
