### ISSUE TITLE
Bugs out when also using Illandril's Token HUD Scaler

### ISSUE THREAD

**Issue by GambetTV** [krysztalzg/ThandulsTogglableEffects#8]
Love the module, but it bugs out when also using Illandril's Token HUD Scaler module. Basically creates 2 versions of it, one at the normal size, and one at the scaled size from Illandril's module. Not sure which module is causing the error so I'm posting this to both modules.

**Comment by kszczepanskidev** [comment]
Interesting, my module only adds an Active Effect to the actor, I'm not doing anything with token and token statuses 🤔
