### ISSUE TITLE
Can't toggle rage on a token without the Barbarian class

### ISSUE THREAD

**Issue by illandril** [krysztalzg/ThandulsTogglableEffects#9]
An uncaught TypeError is thrown trying to check to see if the actor is a "Path of the Totem Warrior" or not.

```
effects.js:241 Uncaught TypeError: Cannot read property 'data' of undefined
    at Function.rage (effects.js:241)
    at Function.getEffectForActor (effects.js:53)
    at HTMLLIElement.handleEffectToggleEvent (effects.js:29)
```

```
240        const classItem = actor.data.items.filter(isBarbarianClassItem)[0];
241        if(classItem.data.subclass === "Path of the Totem Warrior") {
```

Note: I don't know if anyone would ever actually want to do this or not in practice - I only noticed it because I was clicking on random effects testing my mod (re: illandril/FoundryVTT-token-hud-scale#10).

**Comment by kszczepanskidev** [comment]
Thanks for checking it out, it checks if actor have Barbarian class on the sheet, but it was missing stopping with warning message
